# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'xolox/vim-easytags'

[[plugins]]
repo = 'eagletmt/neco-ghc'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\    "_" : {
\        'runner'    : 'vimproc',
\        'runner/vimproc/updatetime' : 60,
\        'outputter' : 'error',
\        'outputter/error/success' : 'buffer',
\        'outputter/error/error'   : 'quickfix',
\        'outputter/buffer/split'  : ':rightbelow 8sp',
\        'outputter/buffer/close_on_empty' : 1,
\    },
\   'haskell' : { 'type' : 'haskell/stack' },
\   'haskell/stack' : {
\       'command' : 'stack',
\       'exec' : '%c %o %s %a',
\       'cmdopt' : 'runghc',
\   },
\}
'''

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'haya14busa/vim-easymotion'

[[plugins]]
repo = 'haya14busa/incsearch.vim'
